### ISSUE TITLE
[Bug] Fullscreen not working

### ISSUE THREAD

**Issue by vttc08** [vttc08/docker-mcaselector#1]
### Current Behavior

When selecting the main window in `main-window-selection.xml`, the app initially fullscreen (screenshot 1), but when opening other Windows such as `About` or a file dialog to choose a world, the app now runs in a smaller size with no options to resize (screenshot 2 and 3).

![Screenshot_1](https://github.com/user-attachments/assets/9c14853c-3699-4956-8b2a-6fab5839f9d0)
![Screenshot_2](https://github.com/user-attachments/assets/2d9c6740-7a89-4646-b247-52e65c2802b3)
![Screenshot_3](https://github.com/user-attachments/assets/bc0ae7dd-879f-49de-b3bc-110a022f6763)
b.com/user-attachments/assets/9c14853c-3699-4956-8b2a-6fab5839f9d0)

### Expected Behavior

The app main should remain fullscreen with same window size. 

### Steps To Reproduce

Run `obxprop | grep "^_OB_APP"` in the container and select the main window.
Get result 
```shell
_OB_APP_TYPE(UTF8_STRING) = "normal"
_OB_APP_TITLE(UTF8_STRING) = "MCA Selector 2.4.1"
_OB_APP_GROUP_CLASS(UTF8_STRING) = "Java"
_OB_APP_GROUP_NAME(UTF8_STRING) = "java"
_OB_APP_CLASS(UTF8_STRING) = "net.querz.mcaselector.ui.Window"
_OB_APP_NAME(UTF8_STRING) = "net.querz.mcaselector.ui.Window"
_OB_APP_ROLE(UTF8_STRING) = 
```
Follow the instruction in [here](https://github.com/jlesage/docker-baseimage-gui?tab=readme-ov-file#maximizing-only-the-main-window) and added into `main-window-selection.xml`
```xml
<Type>normal</Type>
<Name>net.querz.mcaselector.ui.Windows</Name>
```
Build the container and start app.

### Environment

- OS: Debian Linux 
- OS version: 12
- CPU: Intel Genuine 0000
- Docker version: 24.0.5, build ced0996
- Device model: n/a
- Browser/OS: Chrome 126/Windows 10

### Container creation

```yaml
version: '3'
services:
  mcaselector:
    image: vttc08/mcaselector
    container_name: mcaselector
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - "/docker/minecraft-server/world:/world:rw"
      - "/appdata/mcaselector:/config:rw"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=America/New_York
      - KEEP_APP_RUNNING=1
      - MEMORY=4G
    restart: unless-stopped
```

### Container log

```text
[xcompmgr    ] error 138: BadRegion request 138 minor 14 serial 2366
[xcompmgr    ] error 3: BadWindow (invalid Window parameter) request 20 minor 0 serial 2504
```

### Anything else?

The repo consists of the [Dockerfile](https://github.com/vttc08/docker-mcaselector/blob/master/Dockerfile) which is used to build this container.

After the window size has changed, running `obxprop | grep "^_OB_APP"` on the active window still return the same result.
```shell
_OB_APP_TYPE(UTF8_STRING) = "normal"
_OB_APP_TITLE(UTF8_STRING) = "MCA Selector 2.4.1"
_OB_APP_GROUP_CLASS(UTF8_STRING) = "Java"
_OB_APP_GROUP_NAME(UTF8_STRING) = "java"
_OB_APP_CLASS(UTF8_STRING) = "net.querz.mcaselector.ui.Window"
_OB_APP_NAME(UTF8_STRING) = "net.querz.mcaselector.ui.Window"
_OB_APP_ROLE(UTF8_STRING) = 
```
